# Generated by Django 5.2.7 on 2026-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlog',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='vlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vlog',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vlog',
            name='video_url',
        ),
        migrations.AddField(
            model_name='vlog',
            name='content',
            field=models.TextField(default='No content yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlog',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
