# Generated by Django 5.2.7 on 2026-01-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0002_rename_author_vlog_user_remove_vlog_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlog',
            options={'ordering': ['-created_at']},
        ),
    ]
